//==============================================================================
//      File:           $URL$
//      Version:        Automatically generated by 'System Verilog to VPI' script
//      Author:         Script By Tom Golubev
//      Copyright:      Copyright 2005-2009 UC Santa Cruz
//==============================================================================

//==============================================================================
//     Section:        License
//==============================================================================
//      Copyright (c) 2005-2009, Regents of the University of California
//      All rights reserved.
//
//      Redistribution and use in source and binary forms, with or without modification,
//      are permitted provided that the following conditions are met:
//
//              - Redistributions of source code must retain the above copyright notice,
//                      this list of conditions and the following disclaimer.
//              - Redistributions in binary form must reproduce the above copyright
//                      notice, this list of conditions and the following disclaimer
//                      in the documentation and/or other materials provided with the
//                      distribution.
//             - Neither the name of the University of California, Santa Cruz nor the
//                      names of its contributors may be used to endorse or promote
//                     products derived from this software without specific prior
//                      written permission.
//
//      THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
//      ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
//      WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
//      DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
//      ANY DIRECT, INDIRECT, INCIDENTAL,SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
//      (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//      LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
//      ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//      (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//      SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//==============================================================================


/****************************************************************************
    Description: TestBench Verilog File for alu_ref_design.v
 
****************************************************************************/


import retry_common::*;
import rnet_common::*;
import alu_types::*;

`ifdef USE_SDF1
 `timescale 1ns / 1fs
 `include "asic/alu_ref_design_netlist.v"
`endif

module  alu_ref_design_tb();

  //Start DUT variable definition
  BoolType		reset;
  RingPacketType		switch_2_block;
  BoolType		switch_2_blockValid;
  BoolType		switch_2_blockRetry;
  ReclkIOType		rci0;
  ReclkIOType		rco1;
  RingPacketType		block_2_switch;
  BoolType		block_2_switchValid;
  BoolType		block_2_switchRetry;

  logic mclk;

  real                                  val;
  real                                  val_clk_delay;
  real                                  val_set_delay;
  real                                  val_check_delay;
  real                                  val_clk_width;
  int                                   tb_cycle;
  int                                   tb_tune_val;
  logic                            clk;
	logic                            CLK_PAD;
	assign CLK_PAD = clk;

  alu_ref_design alu_ref_design_dut(.*);
  

  initial begin
    if (!$value$plusargs("clk=%g",val)) begin
      val                               = 100;
    end
    if (!$value$plusargs("clk_delay=%g",val_clk_delay)) begin
      val_clk_delay                     = 0.0/10;
    end
    if (!$value$plusargs("set_delay=%g",val_set_delay)) begin
      val_set_delay                     = 5.2/10;
    end
    if (!$value$plusargs("check_delay=%g",val_check_delay)) begin
      val_check_delay                     = 9.6/10;
    end
    if (!$value$plusargs("clk_width=%g",val_clk_width)) begin
      val_clk_width                      = 5.0/10;
    end

    $display("full clock %5.3f GHz +clk=%g +clk_delay=%.2f +clk_width=%.2f +set_delay=%.2f +check_delay=%.2f", 1.0/val, val, val_clk_delay, val_clk_width, val_set_delay, val_check_delay);
  end

`ifdef USE_SDF1
  initial begin
    $sdf_annotate("asic/alu_ref_design.sdf", alu_ref_design_dut);
  end
`endif

  initial begin
		// Not all the blocks use reset (assume reset set for simpler testcases
		reset = 1'b1;
    mclk                                = 1'b1;
    clk                                 = 1'b1;
    
    $alu_ref_design_init (reset,
		 switch_2_block,
		 switch_2_blockValid,
		 switch_2_blockRetry,
		 rci0,
		 rco1,
		 block_2_switch,
		 block_2_switchValid,
		 block_2_switchRetry,
	   tb_cycle, 
     tb_tune_val);// /init fn


`ifdef USE_SAIF

    //$read_rtl_saif("fpu_dump.saif","alu_ref_design_tb.alu_ref_design_dut");
    $set_gate_level_monitoring("rtl_on");
    $set_toggle_region("alu_ref_design_tb.alu_ref_design_dut");
    $toggle_start();

    $dumpfile("alu_ref_design_dump.vcd");
    $dumpvars();
    $dumpon;

    #(100000*val_clk_delay)
    #10
    $toggle_stop();
    #10$toggle_report("alu_ref_design_dump.saif", 1.0e-12, "alu_ref_design_tb.alu_ref_design_dut");
    //$dumpoff;
    $dumpflush;
    $display("Done with the SAIF/VCD sampling\n");
    $finish;
`endif
  end

  always begin
    #(val/2) mclk                   = ~mclk;
  end

`ifdef USE_SDF
  always @(posedge clk) begin // Sync with master clock
    // Pulse width
    #(val_clk_width*val) clk                   = 1'b0;
  end

  always @(posedge mclk) begin
    // pulse delay
    #(val_clk_delay*val) clk                   = 1'b1;
  end
`else
  always @(posedge clk) begin // Sync with master clock
    // Pulse width
    #(val/2) clk                   = 1'b0;
  end

  always @(posedge mclk) begin
    #(val) clk                   = 1'b1;
  end
`endif

`ifdef USE_SDF
  always @(posedge clk) begin
    #(val_set_delay*val)
    $alu_ref_design_set();
  end
  always @(posedge clk) begin
    #(val_check_delay*val)
    $alu_ref_design_check();
  end
`else
  always @(posedge clk) begin
    #(51*val/100) $alu_ref_design_set();
    #(40*val/100) $alu_ref_design_check();
  end
`endif
 
endmodule
 
